### ISSUE TITLE
ModuleNotFoundError: No module named 'llama_index.embeddings.langchain'

### ISSUE THREAD

**Issue by cphilibien** [bchaipats/notebooks#1]
Hello I follow your medium article but I have this error: ModuleNotFoundError: No module named 'llama_index.embeddings.langchain' could you help me iwth this issue?

Thank you
Carole

**Comment by bchaipats** [comment]
Hi,

The error is caused by the newer version of `llama-index`. They've rearranged and split their package into multiple ones, and we have to manually install them.

I've fixed the problem and pushed a commit of the new version of the notebook. Please re-create a Python environment and try running the notebook again.

If you still face any problems, please let me know. Also, thank you for following!
